[tool.poetry]
name = "rcs-project"
version = "0.1.0"
description = ""
authors = ["Olit <93828847+OlitHub@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
